import type { ReadinessReport } from '../agents/analyzer/schema.ts';
import type { DevPlan } from '../agents/planner/schema.ts';
import type { Changeset } from '../agents/coder/schema.ts';
import type { PipelineState, TelemetryData } from '../types/pipeline.types.ts';
import { TransientAgentError } from '../sdk/errors.ts';

// ---------------------------------------------------------------------------
// DevOps comment formatters — HTML for posting to work item comments
// ---------------------------------------------------------------------------

function esc(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/**
 * Format the Analyzer's readiness report as a DevOps work item comment (HTML).
 */
export function formatReadinessComment(
  workItemId: number,
  report: ReadinessReport,
): string {
  const icon = report.verdict === 'proceed' ? '✅' : '❌';
  const parts: string[] = [];

  parts.push(`<h2>${icon} Readiness Assessment — Work Item #${workItemId}</h2>`);
  parts.push(`<p><b>Verdict:</b> ${esc(report.verdict)}</p>`);
  parts.push(textToHtml(report.summary));

  if (report.gaps.length > 0) {
    parts.push(`<h3>Gaps Found</h3>`);
    parts.push(`<table><tr><th>Field</th><th>Severity</th><th>Status</th><th>Question</th><th>Resolution</th></tr>`);
    for (const gap of report.gaps) {
      const status = gap.resolvedByAgent ? '✅ Resolved' : '⚠️ Needs input';
      const resolution = gap.resolution ? esc(gap.resolution) : '-';
      parts.push(`<tr><td><b>${esc(gap.field)}</b></td><td>${esc(gap.severity)}</td><td>${status}</td><td>${esc(gap.question)}</td><td>${resolution}</td></tr>`);
    }
    parts.push(`</table>`);
  }

  if (report.enrichedContext.codebaseInsights.length > 0) {
    parts.push(`<h3>Codebase Insights</h3>`);
    parts.push(`<ul>`);
    for (const insight of report.enrichedContext.codebaseInsights) {
      parts.push(`<li>${esc(insight)}</li>`);
    }
    parts.push(`</ul>`);
  }

  parts.push(`<hr><em>Generated by DevOps Pipeline</em>`);
  return parts.join('\n');
}

/** Escape a value for a Markdown table cell (pipes + newlines break the table). */
function mdCell(v: unknown): string {
  return String(v ?? '').replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
}

/**
 * Format the approved dev plan as a DevOps work item comment (Markdown).
 * Posted with `format=markdown` (see postWorkItemComment): headings render with
 * real hierarchy and the long per-object descriptions collapse into <details>, so
 * the comment is a scannable summary + table rather than a wall of text.
 */
export function formatPlanComment(
  workItemId: number,
  plan: DevPlan,
): string {
  const L: string[] = [];

  L.push(`## 🤖 Dev Plan — Work Item #${workItemId}`, '');
  L.push(plan.summary.trim(), '');

  // Objects overview table
  const verb = plan.objects.some(o => o.action === 'create') ? 'create/' : '';
  L.push(`### Objects to ${verb}modify`, '');
  L.push(`| Action | Type | ID | Name |`, `| --- | --- | --- | --- |`);
  for (const obj of plan.objects) {
    const action = obj.action === 'create' ? '🆕 create' : '✏️ modify';
    L.push(`| ${action} | ${mdCell(obj.objectType)} | ${mdCell(obj.objectId ?? '(new)')} | ${mdCell(obj.objectName)} |`);
  }
  L.push('');

  // Per-object detail — collapsed so the comment stays scannable
  L.push(`### Object details`, '');
  for (const obj of plan.objects) {
    const action = obj.action === 'create' ? '🆕' : '✏️';
    const id = obj.objectId ?? '(new)';
    L.push(
      `<details><summary><b>${esc(obj.objectName)}</b> — ${action} ${esc(obj.objectType)} ${esc(String(id))}</summary>`,
      '',
      obj.description.trim(),
      '',
      `</details>`,
      '',
    );
  }

  // Risk
  L.push(`### Risk: ${esc(plan.riskAssessment.level)}`, '');
  for (const factor of plan.riskAssessment.factors) L.push(`- ${factor}`);
  L.push('');

  // Test scenarios — collapsed
  L.push(`<details><summary><b>Test Scenarios (${plan.testScenarios.length})</b></summary>`, '');
  plan.testScenarios.forEach((t, i) => L.push(`${i + 1}. **${t.name}** — ${t.description}`));
  L.push('', `</details>`, '');

  L.push(`**Complexity:** ${esc(plan.estimatedComplexity)}`, '');
  L.push(`---`, `*To approve: add tag* \`plan-approved\` &nbsp;·&nbsp; *To request changes: comment* \`/rerun-plan\` *with feedback*`, '');
  L.push(`*Generated by DevOps Pipeline*`);

  return L.join('\n');
}

/**
 * Format the changeset summary for inclusion in PR description or comments.
 */
export function formatChangesetSummary(changeset: Changeset, ciRunUrl?: string): string {
  const lines = [
    `### Changes`,
    ``,
    `**Branch:** \`${changeset.branchName}\``,
    ``,
  ];

  if (changeset.filesCreated.length > 0) {
    lines.push(`**Files created:**`);
    for (const f of changeset.filesCreated) {
      lines.push(`- \`${f}\``);
    }
    lines.push(``);
  }

  if (changeset.filesModified.length > 0) {
    lines.push(`**Files modified:**`);
    for (const f of changeset.filesModified) {
      lines.push(`- \`${f}\``);
    }
    lines.push(``);
  }

  const ciStatus = changeset.ciResult === 'passed' ? '✅ Passed'
    : changeset.ciResult === 'failed' ? '❌ Failed'
    : '⏸️ Not run';

  if (ciRunUrl) {
    lines.push(`**CI Pipeline:** [${ciStatus}](${ciRunUrl})`);
  } else {
    lines.push(`**CI Pipeline:** ${ciStatus}${changeset.ciRunId ? ` (Run #${changeset.ciRunId})` : ''}`);
  }

  return lines.join('\n');
}

/**
 * Convert plain text with light markdown to readable HTML.
 * Handles: `- ` bullet lists, `N. ` ordered lists,
 * `**bold**`, `\`code\``, and blank-line paragraph breaks.
 */
function textToHtml(text: string): string {
  const lines = text.split('\n');
  const out: string[] = [];
  let listType: 'ul' | 'ol' | null = null;

  function inline(s: string): string {
    return esc(s)
      .replace(/\*\*(.+?)\*\*/g, '<b>$1</b>')
      .replace(/`([^`]+)`/g, '<code>$1</code>');
  }

  function closeList() {
    if (listType) { out.push(`</${listType}>`); listType = null; }
  }

  function openList(type: 'ul' | 'ol') {
    if (listType !== type) { closeList(); out.push(`<${type}>`); listType = type; }
  }

  for (const raw of lines) {
    const line = raw.trim();

    if (line === '') {
      closeList();
      continue;
    }

    const olMatch = line.match(/^(\d+)\.\s+(.*)/);
    if (line.startsWith('- ')) {
      openList('ul');
      out.push(`<li>${inline(line.slice(2))}</li>`);
    } else if (olMatch) {
      openList('ol');
      out.push(`<li>${inline(olMatch[2]!)}</li>`);
    } else {
      closeList();
      out.push(`<p>${inline(line)}</p>`);
    }
  }

  closeList();
  return out.join('\n');
}

/**
 * Format a pipeline error as a DevOps work item comment (HTML).
 */
export function formatErrorComment(
  workItemId: number,
  stageName: string,
  error: Error,
): string {
  const parts: string[] = [];
  parts.push(`<h2>🚨 Pipeline Error — Work Item #${workItemId}</h2>`);
  parts.push(`<p><b>Stage:</b> <code>${esc(stageName)}</code></p>`);
  parts.push(textToHtml(error.message));

  if (error instanceof TransientAgentError) {
    parts.push(`<p><b>Retry attempts:</b> ${error.attempts}</p>`);
  }

  parts.push(`<hr>`);
  parts.push(`<h3>Recovery Options</h3>`);
  parts.push(`<ol>`);
  parts.push(`<li><b>Resume from failed stage</b> — use the dashboard "Continue" action (preferred)</li>`);
  parts.push(`<li><b>CLI resume</b> — <code>bun run pipeline -- continue --work-item ${workItemId}</code></li>`);
  parts.push(`<li><b>Restart from scratch</b> — re-tag with <code>analyse</code> (last resort)</li>`);
  parts.push(`</ol>`);
  return parts.join('\n');
}

/**
 * Format a telemetry summary for CLI display.
 */
export function formatTelemetrySummary(telemetry: TelemetryData): string {
  const lines = [
    `Pipeline Cost Summary`,
    `─────────────────────`,
    `Total cost:     $${telemetry.totalCostUsd.toFixed(4)}`,
    `Total duration: ${(telemetry.totalDurationMs / 1000).toFixed(1)}s`,
    ``,
    `Stage                 Cost       Duration   Turns`,
    `────────────────────  ─────────  ─────────  ─────`,
  ];

  for (const s of telemetry.stages) {
    const name = s.name.padEnd(20);
    const cost = `$${s.costUsd.toFixed(4)}`.padEnd(9);
    const dur = `${(s.durationMs / 1000).toFixed(1)}s`.padEnd(9);
    lines.push(`${name}  ${cost}  ${dur}  ${s.turns}`);
  }

  return lines.join('\n');
}
