import type { ReadinessReport } from '../agents/analyzer/schema.ts';
import type { DevPlan } from '../agents/planner/schema.ts';
import type { Changeset } from '../agents/coder/schema.ts';
import type { PipelineState, TelemetryData } from '../types/pipeline.types.ts';
import { TransientAgentError } from '../sdk/errors.ts';
import { recurringFindings } from '../pipeline/revision-loop.ts';

// ---------------------------------------------------------------------------
// DevOps comment formatters — HTML for posting to work item comments
// ---------------------------------------------------------------------------

function esc(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/**
 * Format the Analyzer's readiness report as a DevOps work item comment (HTML).
 */
export function formatReadinessComment(
  workItemId: number,
  report: ReadinessReport,
): string {
  const icon = report.verdict === 'proceed' ? '✅' : '❌';
  const parts: string[] = [];

  parts.push(`<h2>${icon} Readiness Assessment — Work Item #${workItemId}</h2>`);
  parts.push(`<p><b>Verdict:</b> ${esc(report.verdict)}</p>`);
  parts.push(textToHtml(report.summary));

  if (report.gaps.length > 0) {
    parts.push(`<h3>Gaps Found</h3>`);
    parts.push(`<table><tr><th>Field</th><th>Severity</th><th>Status</th><th>Question</th><th>Resolution</th></tr>`);
    for (const gap of report.gaps) {
      const status = gap.resolvedByAgent ? '✅ Resolved' : '⚠️ Needs input';
      const resolution = gap.resolution ? esc(gap.resolution) : '-';
      parts.push(`<tr><td><b>${esc(gap.field)}</b></td><td>${esc(gap.severity)}</td><td>${status}</td><td>${esc(gap.question)}</td><td>${resolution}</td></tr>`);
    }
    parts.push(`</table>`);
  }

  if (report.enrichedContext.codebaseInsights.length > 0) {
    parts.push(`<h3>Codebase Insights</h3>`);
    parts.push(`<ul>`);
    for (const insight of report.enrichedContext.codebaseInsights) {
      parts.push(`<li>${esc(insight)}</li>`);
    }
    parts.push(`</ul>`);
  }

  parts.push(`<hr><em>Generated by DevOps Pipeline</em>`);
  return parts.join('\n');
}

/** Escape a value for a Markdown table cell (pipes + newlines break the table). */
function mdCell(v: unknown): string {
  return String(v ?? '').replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
}

/**
 * Format the approved dev plan as a DevOps work item comment (Markdown).
 * Posted with `format=markdown` (see postWorkItemComment): headings render with
 * real hierarchy and the long per-object descriptions collapse into <details>, so
 * the comment is a scannable summary + table rather than a wall of text.
 */
export function formatPlanComment(
  workItemId: number,
  plan: DevPlan,
): string {
  const L: string[] = [];

  L.push(`## 🤖 Dev Plan — Work Item #${workItemId}`, '');
  L.push(plan.summary.trim(), '');

  // Objects overview table
  const verb = plan.objects.some(o => o.action === 'create') ? 'create/' : '';
  L.push(`### Objects to ${verb}modify`, '');
  L.push(`| Action | Type | ID | Name |`, `| --- | --- | --- | --- |`);
  for (const obj of plan.objects) {
    const action = obj.action === 'create' ? '🆕 create' : '✏️ modify';
    L.push(`| ${action} | ${mdCell(obj.objectType)} | ${mdCell(obj.objectId ?? '(new)')} | ${mdCell(obj.objectName)} |`);
  }
  L.push('');

  // Per-object detail — collapsed so the comment stays scannable
  L.push(`### Object details`, '');
  for (const obj of plan.objects) {
    const action = obj.action === 'create' ? '🆕' : '✏️';
    const id = obj.objectId ?? '(new)';
    L.push(
      `<details><summary><b>${esc(obj.objectName)}</b> — ${action} ${esc(obj.objectType)} ${esc(String(id))}</summary>`,
      '',
      obj.description.trim(),
      '',
      `</details>`,
      '',
    );
  }

  // Risk
  L.push(`### Risk: ${esc(plan.riskAssessment.level)}`, '');
  for (const factor of plan.riskAssessment.factors) L.push(`- ${factor}`);
  L.push('');

  // Test scenarios — collapsed
  L.push(`<details><summary><b>Test Scenarios (${plan.testScenarios.length})</b></summary>`, '');
  plan.testScenarios.forEach((t, i) => L.push(`${i + 1}. **${t.name}** — ${t.description}`));
  L.push('', `</details>`, '');

  L.push(`**Complexity:** ${esc(plan.estimatedComplexity)}`, '');
  L.push(`---`, `*To approve: add tag* \`plan-approved\` &nbsp;·&nbsp; *To request changes: comment* \`/rerun-plan\` *with feedback*`, '');
  L.push(`*Generated by DevOps Pipeline*`);

  return L.join('\n');
}

/**
 * Format the changeset summary for inclusion in PR description or comments.
 */
export function formatChangesetSummary(changeset: Changeset, ciRunUrl?: string): string {
  const lines = [
    `### Changes`,
    ``,
    `**Branch:** \`${changeset.branchName}\``,
    ``,
  ];

  if (changeset.filesCreated.length > 0) {
    lines.push(`**Files created:**`);
    for (const f of changeset.filesCreated) {
      lines.push(`- \`${f}\``);
    }
    lines.push(``);
  }

  if (changeset.filesModified.length > 0) {
    lines.push(`**Files modified:**`);
    for (const f of changeset.filesModified) {
      lines.push(`- \`${f}\``);
    }
    lines.push(``);
  }

  const ciStatus = changeset.ciResult === 'passed' ? '✅ Passed'
    : changeset.ciResult === 'failed' ? '❌ Failed'
    : '⏸️ Not run';

  if (ciRunUrl) {
    lines.push(`**CI Pipeline:** [${ciStatus}](${ciRunUrl})`);
  } else {
    lines.push(`**CI Pipeline:** ${ciStatus}${changeset.ciRunId ? ` (Run #${changeset.ciRunId})` : ''}`);
  }

  return lines.join('\n');
}

/**
 * Convert plain text with light markdown to readable HTML.
 * Handles: `- ` bullet lists, `N. ` ordered lists,
 * `**bold**`, `\`code\``, and blank-line paragraph breaks.
 */
function textToHtml(text: string): string {
  const lines = text.split('\n');
  const out: string[] = [];
  let listType: 'ul' | 'ol' | null = null;

  function inline(s: string): string {
    return esc(s)
      .replace(/\*\*(.+?)\*\*/g, '<b>$1</b>')
      .replace(/`([^`]+)`/g, '<code>$1</code>');
  }

  function closeList() {
    if (listType) { out.push(`</${listType}>`); listType = null; }
  }

  function openList(type: 'ul' | 'ol') {
    if (listType !== type) { closeList(); out.push(`<${type}>`); listType = type; }
  }

  for (const raw of lines) {
    const line = raw.trim();

    if (line === '') {
      closeList();
      continue;
    }

    const olMatch = line.match(/^(\d+)\.\s+(.*)/);
    if (line.startsWith('- ')) {
      openList('ul');
      out.push(`<li>${inline(line.slice(2))}</li>`);
    } else if (olMatch) {
      openList('ol');
      out.push(`<li>${inline(olMatch[2]!)}</li>`);
    } else {
      closeList();
      out.push(`<p>${inline(line)}</p>`);
    }
  }

  closeList();
  return out.join('\n');
}


// ---------------------------------------------------------------------------
// Stalled revision loop — the shared diagnostic
//
// A loop can stop for two reasons and both used to tell the human almost
// nothing. Budget exhaustion posted a bare "exhausted N attempts without
// approval" plus generic recovery options: no findings, no trend, nothing to
// decide — so the only available move was to resume and hope. The convergence
// escalation and the exhaustion error now render the SAME summary, because the
// human needs identical information either way: what is being objected to, is it
// getting better, and what is being asked of them.
// ---------------------------------------------------------------------------

export interface StalledLoopSummary {
  loop: string;
  /** Issue count per round, oldest first. Empty when the reviewer reported none. */
  issueCounts: number[];
  /** Findings raised in more than one round — what iteration is failing to resolve. */
  recurring: string[];
  /** Findings from the most recent round only, worst-first. */
  latest: Array<{ severity: string; filePath?: string; comment: string }>;
  /** The last reviewer's own summary. */
  lastFeedback?: string;
  /** What the last reviewer told the producer to do. */
  revisionInstructions?: string;
  attempts?: number;
}

const SEVERITY_ORDER = ['critical', 'major', 'minor', 'suggestion'];

/**
 * How many outstanding findings to list, and how much of each.
 *
 * Real reviewer findings run to paragraph length — WI 63396's last round had 22,
 * several over 1,500 characters. Rendered in full that is a wall of text nobody
 * reads, which fails the same way the bare error did. The comment's job is to
 * support a decision, not to reproduce the review: blocking findings only,
 * trimmed to their opening claim, with the count of what was left out.
 */
const MAX_LISTED_FINDINGS = 8;
const MAX_FINDING_CHARS = 320;

/** Trim to a whole word near the limit, marking that it was cut. */
export function truncateFinding(text: string, limit = MAX_FINDING_CHARS): string {
  if (text.length <= limit) return text;
  const cut = text.slice(0, limit);
  const lastSpace = cut.lastIndexOf(' ');
  return (lastSpace > limit * 0.6 ? cut.slice(0, lastSpace) : cut).trimEnd() + '…';
}

/** Findings that would block: critical + major. Minors never gate a verdict. */
export function blockingFindings<T extends { severity: string }>(findings: T[]): T[] {
  return findings.filter((f) => f.severity === 'critical' || f.severity === 'major');
}

/**
 * Pull everything a human needs to unblock a stalled loop out of accumulated
 * state. Returns null when the loop left no reviews to report on — there is
 * genuinely nothing to say, and inventing a section would be worse.
 *
 * Reads `codeReviews` structurally: it is typed as the shared `ReviewVerdict`
 * minimum, and this formatter must not import agent output schemas.
 */
export function summarizeStalledLoop(
  state: PipelineState | undefined,
  loop: string,
): StalledLoopSummary | null {
  if (!state) return null;
  const reviews = (state.codeReviews ?? []) as Array<{
    verdict?: string;
    feedback?: string;
    revisionInstructions?: string;
    issues?: Array<{ severity?: string; filePath?: string; comment?: string }>;
  }>;
  if (reviews.length === 0) return null;

  const perRound = reviews.map((r) =>
    (r.issues ?? []).map((i) => i.comment ?? '').filter(Boolean),
  );
  const last = reviews.at(-1);

  const latest = [...(last?.issues ?? [])]
    .map((i) => ({
      severity: i.severity ?? 'unknown',
      filePath: i.filePath,
      comment: i.comment ?? '',
    }))
    .filter((i) => i.comment)
    .sort((a, b) => {
      const ai = SEVERITY_ORDER.indexOf(a.severity);
      const bi = SEVERITY_ORDER.indexOf(b.severity);
      return (ai < 0 ? SEVERITY_ORDER.length : ai) - (bi < 0 ? SEVERITY_ORDER.length : bi);
    });

  return {
    loop,
    issueCounts: state.revisionIssueCounts?.[loop]
      ?? reviews.map((r) => (r.issues ?? []).length),
    recurring: recurringFindings(perRound),
    latest,
    lastFeedback: last?.feedback,
    revisionInstructions: last?.revisionInstructions,
    attempts: state.revisionAttempts?.[loop],
  };
}

/** Is the trend flat or worsening? Decides which reading we present. */
function trendIsFlat(counts: number[]): boolean {
  if (counts.length < 2) return false;
  return counts.at(-1)! >= counts[0]!;
}

/**
 * Format a pipeline error as a DevOps work item comment (HTML).
 */
export function formatErrorComment(
  workItemId: number,
  stageName: string,
  error: Error,
  state?: PipelineState,
): string {
  const parts: string[] = [];
  parts.push(`<h2>🚨 Pipeline Error — Work Item #${workItemId}</h2>`);
  parts.push(`<p><b>Stage:</b> <code>${esc(stageName)}</code></p>`);
  parts.push(textToHtml(error.message));

  if (error instanceof TransientAgentError) {
    parts.push(`<p><b>Retry attempts:</b> ${error.attempts}</p>`);
  }

  // A revision loop that ran out of budget is not a crash — it is a stalled
  // negotiation. "Resume and hope" is not a decision anyone can make without
  // seeing what is being objected to, so attach the same diagnostic the
  // convergence escalation posts.
  const stalled = summarizeStalledLoop(state, stageName);
  if (stalled) {
    parts.push(renderStalledLoopHtml(stalled));
  }

  parts.push(`<hr>`);
  parts.push(`<h3>Recovery Options</h3>`);
  parts.push(`<ol>`);
  if (stalled) {
    // Lead with the option that carries a decision. A bare resume re-runs the
    // producer against the same reviewers that just deadlocked.
    parts.push(
      `<li><b>Answer and resume</b> — comment `
        + `<code>/fix &lt;which findings to fix, which to drop, and why&gt;</code>. `
        + `This is the only option that changes the inputs.</li>`,
    );
  }
  parts.push(
    `<li><b>Resume from failed stage</b> — use the dashboard "Continue" action`
      + `${stalled ? ' (retries with the same inputs)' : ' (preferred)'}</li>`,
  );
  parts.push(`<li><b>CLI resume</b> — <code>bun run pipeline -- continue --work-item ${workItemId}</code></li>`);
  parts.push(`<li><b>Restart from scratch</b> — re-tag with <code>analyse</code> (last resort)</li>`);
  parts.push(`</ol>`);
  return parts.join('\n');
}

/** The stalled-loop diagnostic as HTML, for the error comment. */
function renderStalledLoopHtml(s: StalledLoopSummary): string {
  const p: string[] = [];
  p.push(`<hr>`);
  p.push(`<h3>Why it is stuck</h3>`);

  if (s.issueCounts.length > 0) {
    p.push(
      `<p><b>Findings per round:</b> <code>${s.issueCounts.join(' → ')}</code>`
        + (trendIsFlat(s.issueCounts)
          ? ` — not going down. The reviewers are not converging on this change.</p>`
          : ` — falling, but the attempt budget ran out first.</p>`),
    );
  }

  if (s.recurring.length > 0) {
    p.push(`<h4>Raised in more than one round</h4>`);
    p.push(`<ul>`);
    for (const f of s.recurring) p.push(`<li>${esc(f)}</li>`);
    p.push(`</ul>`);
  } else if (s.issueCounts.length > 1) {
    p.push(
      `<p><i>No finding repeated across rounds — the reviewers raised <b>different</b> `
        + `objections each time. That usually means the target is underspecified rather `
        + `than the code being wrong.</i></p>`,
    );
  }

  const blocking = blockingFindings(s.latest);
  if (blocking.length > 0) {
    p.push(`<h4>Blocking after the last round (${blocking.length} of ${s.latest.length} findings)</h4>`);
    p.push(`<ul>`);
    for (const i of blocking.slice(0, MAX_LISTED_FINDINGS)) {
      const where = i.filePath ? ` <code>${esc(i.filePath)}</code>` : '';
      p.push(`<li><b>${esc(i.severity)}</b>${where} — ${esc(truncateFinding(i.comment))}</li>`);
    }
    const hidden = blocking.length - MAX_LISTED_FINDINGS;
    if (hidden > 0) {
      p.push(`<li><i>…and ${hidden} more blocking — see the full review in the pipeline logs</i></li>`);
    }
    p.push(`</ul>`);
  }

  if (s.revisionInstructions) {
    p.push(`<h4>What the reviewer last asked for</h4>`);
    p.push(textToHtml(s.revisionInstructions));
  } else if (s.lastFeedback) {
    p.push(`<h4>Last reviewer summary</h4>`);
    p.push(textToHtml(s.lastFeedback));
  }

  p.push(`<h3>What you need to decide</h3>`);
  p.push(`<ul>`);
  p.push(`<li>Which of the findings above are <b>real and worth fixing</b>?</li>`);
  p.push(`<li>Which are <b>wrong or out of scope</b>, so the coder should stop trying to satisfy them?</li>`);
  p.push(`<li>Anything the reviewers are <b>missing or misreading</b> about the intent?</li>`);
  p.push(`</ul>`);
  return p.join('\n');
}

// ---------------------------------------------------------------------------
// Pipeline comment detection — used to filter out bot-generated comments
// when scanning work item discussion for human feedback. Lives here (not in
// the transport layer) because the signatures encode what THESE formatters
// emit — `formatReadinessComment`, `formatPlanComment`, `formatErrorComment`.
// ---------------------------------------------------------------------------

/** HTML signatures that identify pipeline-generated comments */
const PIPELINE_COMMENT_SIGNATURES = [
  'Generated by DevOps Pipeline',
  'Readiness Assessment',
  'Dev Plan',
  'Pipeline Error',
  'Recovery Options',
  // Stalled-loop diagnostics. These comments quote `/fix` as the instruction to
  // the human, so they MUST be recognised as bot output or the rerun scan reads
  // them back as the human's reply.
  'Review not converging',
  'Why it is stuck',
  'What you need to decide',
  'stopped — a decision is needed',
  'Blocking findings',
  'What to decide',
];

export function isPipelineComment(htmlText: string): boolean {
  return PIPELINE_COMMENT_SIGNATURES.some(sig => htmlText.includes(sig));
}

/**
 * Format a telemetry summary for CLI display.
 */
export function formatTelemetrySummary(telemetry: TelemetryData): string {
  const lines = [
    `Pipeline Cost Summary`,
    `─────────────────────`,
    `Total cost:     $${telemetry.totalCostUsd.toFixed(4)}`,
    `Total duration: ${(telemetry.totalDurationMs / 1000).toFixed(1)}s`,
    ``,
    `Stage                 Cost       Duration   Turns`,
    `────────────────────  ─────────  ─────────  ─────`,
  ];

  for (const s of telemetry.stages) {
    const name = s.name.padEnd(20);
    const cost = `$${s.costUsd.toFixed(4)}`.padEnd(9);
    const dur = `${(s.durationMs / 1000).toFixed(1)}s`.padEnd(9);
    lines.push(`${name}  ${cost}  ${dur}  ${s.turns}`);
  }

  return lines.join('\n');
}

/**
 * Escalation posted when a revision loop stops because its findings plateaued.
 *
 * The human needs three things to answer usefully: that iteration stalled rather
 * than failed, which findings keep coming back, and what specifically to reply.
 * Returns null when the state carries no escalation, so it can sit in the
 * stage-keyed formatter map and stay silent on every normal completion.
 */
export function formatConvergenceEscalation(
  workItemId: number,
  state: PipelineState,
): string | null {
  const esc = state.convergenceEscalation;
  if (!esc) return null;

  const L: string[] = [];
  L.push(`## ⚖️ Review not converging — input needed (Work Item #${workItemId})`, '');
  L.push(
    `The **${esc.loop}** loop ran ${esc.issueCounts.length} review rounds and the finding count `
      + `did not go down: **${esc.issueCounts.join(' → ')}**.`,
    '',
  );
  L.push(
    `Iterating further would spend budget without evidence it converges, so the pipeline `
      + `paused here instead of running out its remaining attempts.`,
    '',
  );

  if (esc.recurringFindings.length > 0) {
    L.push(`### Findings raised in more than one round`, '');
    for (const f of esc.recurringFindings) L.push(`- ${f}`);
    L.push('');
  } else {
    L.push(
      `_No finding repeated verbatim across rounds — the reviewers are raising **different** `
        + `objections each round, which is its own signal: the target may be underspecified._`,
      '',
    );
  }

  // The escalation marker carries only counts and recurrences. The actual
  // outstanding findings and the reviewer's own instructions live in state, and
  // they are what makes the ask answerable rather than abstract.
  const stalled = summarizeStalledLoop(state, esc.loop);
  const blocking = blockingFindings(stalled?.latest ?? []);
  if (blocking.length > 0) {
    L.push(`### Blocking after the last round (${blocking.length} of ${stalled!.latest.length} findings)`, '');
    for (const i of blocking.slice(0, MAX_LISTED_FINDINGS)) {
      const where = i.filePath ? ` \`${i.filePath}\`` : '';
      L.push(`- **${i.severity}**${where} — ${truncateFinding(i.comment)}`);
    }
    const hidden = blocking.length - MAX_LISTED_FINDINGS;
    if (hidden > 0) L.push(`- _…and ${hidden} more blocking — see the full review in the pipeline logs_`);
    L.push('');
  }
  if (stalled?.revisionInstructions) {
    L.push(`### What the reviewer last asked for`, '', stalled.revisionInstructions, '');
  }

  L.push(`### What to do`, '');
  L.push(esc.question, '');
  return L.join('\n');
}

// ---------------------------------------------------------------------------
// Stalled-loop comment, Markdown edition
//
// The HTML version was readable but three things fought the reader:
//   - every finding truncated to ~320 chars, so the detail needed to judge one
//     was exactly the part cut off;
//   - the same file repeated on 6 of 8 lines (WI 63396), burying the difference
//     between them in identical prefixes;
//   - nothing to point at. "Which are wrong?" is unanswerable when the reply has
//     to re-describe the finding in prose.
//
// Markdown fixes all three: real heading hierarchy, <details> to carry the FULL
// text without spending vertical space, grouping by file, and stable numbers the
// human can name in a one-line reply.
// ---------------------------------------------------------------------------

const SEVERITY_ICON: Record<string, string> = {
  critical: '🔴',
  major: '🟠',
  minor: '🟡',
  suggestion: '⚪',
};

/**
 * First sentence, for the collapsed summary line. Findings open with their claim
 * and then justify it, so the opening sentence is reliably the part worth
 * scanning — and unlike a character cut it never ends mid-thought.
 */
export function leadSentence(text: string, limit = 160): string {
  const stop = text.search(/\.\s/);
  const first = stop > 0 ? text.slice(0, stop + 1) : text;
  return first.length <= limit ? first : truncateFinding(first, limit);
}

/** `Cloud/Al/Table/Table 6175284 X.al` → `Table 6175284 X.al` */
function baseName(path: string): string {
  return path.split(/[\/]/).pop() ?? path;
}

/**
 * The stalled-loop report as Markdown, or null when the state shows no stalled
 * loop (the caller then falls back to the plain HTML error comment).
 */
export function formatStalledLoopComment(
  workItemId: number,
  stageName: string,
  errorMessage: string,
  state: PipelineState | undefined,
): string | null {
  const s = summarizeStalledLoop(state, stageName);
  if (!s) return null;

  const blocking = blockingFindings(s.latest);
  const L: string[] = [];

  L.push(`## ⚖️ \`${stageName}\` stopped — a decision is needed (Work Item #${workItemId})`, '');
  L.push(errorMessage.trim(), '');

  // --- the trend, in one line -------------------------------------------
  if (s.issueCounts.length > 0) {
    const trend = s.issueCounts.join(' → ');
    L.push(
      trendIsFlat(s.issueCounts)
        ? `**Findings per round:** \`${trend}\` — not going down. The reviewers are not converging on this change.`
        : `**Findings per round:** \`${trend}\` — falling, but the attempt budget ran out first.`,
      '',
    );
  }

  if (s.recurring.length > 0) {
    L.push(`**Raised in more than one round** — iteration is not resolving these:`, '');
    for (const f of s.recurring) L.push(`- ${leadSentence(f)}`);
    L.push('');
  } else if (s.issueCounts.length > 1) {
    L.push(
      `**No finding repeated across rounds.** The reviewers raised *different* objections `
        + `each time, which usually means the target is underspecified rather than the code `
        + `being wrong.`,
      '',
    );
  }

  // --- the findings, numbered and grouped by file ------------------------
  if (blocking.length > 0) {
    L.push(
      `### Blocking findings — ${blocking.length} of ${s.latest.length}`,
      '',
      `Numbered so you can answer by number. Expand any one for the full text.`,
      '',
    );

    // Group by file: on WI 63396 six of eight findings shared one path, and
    // repeating it on every line hid what actually differed between them.
    const groups = new Map<string, typeof blocking>();
    for (const f of blocking) {
      const key = f.filePath ? baseName(f.filePath) : '(no file)';
      groups.set(key, [...(groups.get(key) ?? []), f]);
    }

    // Number AFTER grouping, so the list reads 1..N top to bottom. Numbering by
    // pre-group index left visible gaps (1, 2, 3, 5 …) that read as a bug.
    let n = 0;
    for (const [file, items] of groups) {
      L.push(`**\`${file}\`**`, '');
      for (const it of items) {
        const icon = SEVERITY_ICON[it.severity] ?? '•';
        L.push(
          `<details><summary><b>${++n}.</b> ${icon} <b>${it.severity}</b> — ${esc(leadSentence(it.comment))}</summary>`,
          '',
          it.comment,
          '',
          `</details>`,
          '',
        );
      }
    }
  }

  const nonBlocking = s.latest.length - blocking.length;
  if (nonBlocking > 0) {
    L.push(`_${nonBlocking} further minor/suggestion finding(s) omitted — they do not gate the verdict._`, '');
  }

  if (s.revisionInstructions) {
    L.push(
      `<details><summary><b>What the reviewer last asked for</b></summary>`,
      '',
      s.revisionInstructions,
      '',
      `</details>`,
      '',
    );
  }

  // --- the ask ------------------------------------------------------------
  const example = blocking.length >= 3 ? '1, 3' : blocking.length >= 1 ? '1' : 'none';
  const dropExample = blocking.length >= 2 ? '2' : 'none';
  L.push(`### What to decide`, '');
  L.push(
    `Reply in one comment. Naming the numbers is enough — you do not need to restate the findings.`,
    '',
    '```',
    `/fix fix ${example}; drop ${dropExample} (out of scope); the reviewers are missing <...>`,
    '```',
    '',
  );
  L.push(
    `- Which findings are **real and worth fixing**?`,
    `- Which are **wrong or out of scope**, so the coder stops trying to satisfy them?`,
    `- Anything the reviewers are **missing or misreading** about the intent?`,
    '',
  );
  L.push(
    `Resuming without an answer (dashboard **Continue**, or `
      + `\`bun run pipeline -- continue --work-item ${workItemId}\`) retries against the same `
      + `reviewers with the same inputs.`,
    '',
  );
  return L.join('\n');
}

/**
 * The comment to post for a pipeline error, and the format to post it in.
 *
 * A stalled revision loop gets the Markdown report — it needs headings,
 * collapsibles and numbering that HTML comments render poorly. Everything else
 * keeps the plain HTML error comment: a crashed container has no findings to
 * lay out, and the richer frame would only add ceremony.
 */
export function pipelineErrorComment(
  workItemId: number,
  stageName: string,
  error: Error,
  state?: PipelineState,
): { text: string; format: 'html' | 'markdown' } {
  const stalled = formatStalledLoopComment(workItemId, stageName, error.message, state);
  return stalled
    ? { text: stalled, format: 'markdown' }
    : { text: formatErrorComment(workItemId, stageName, error, state), format: 'html' };
}
